# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Testkube < Formula
  desc "Testkube - your somewhat opinionated and friendly Kubernetes testing framework!"
  homepage "https://testkube.io"
  version "1.10.2"
  license "MIT"

  depends_on "helm"
  depends_on "kubectl"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubeshop/testkube/releases/download/v1.10.2/testkube_1.10.2_macOS_x86_64.tar.gz"
      sha256 "693c14a2ac6739dbc07f329365240d6612f5329e167f7c1dfab81fe202b295d4"

      def install
        bin.install "kubectl-testkube"
        ln_s bin/"kubectl-testkube", bin/"tk"
        ln_s bin/"kubectl-testkube", bin/"testkube"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubeshop/testkube/releases/download/v1.10.2/testkube_1.10.2_macOS_arm64.tar.gz"
      sha256 "343e68781200b763b5e0945ca0258be5897c5274b00a9c08ae91452476a144f4"

      def install
        bin.install "kubectl-testkube"
        ln_s bin/"kubectl-testkube", bin/"tk"
        ln_s bin/"kubectl-testkube", bin/"testkube"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubeshop/testkube/releases/download/v1.10.2/testkube_1.10.2_Linux_arm64.tar.gz"
      sha256 "a8b28832a03bb5e887352f04109dffa63be45307c2f5e5fd7f7f9188dbc33d64"

      def install
        bin.install "kubectl-testkube"
        ln_s bin/"kubectl-testkube", bin/"tk"
        ln_s bin/"kubectl-testkube", bin/"testkube"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kubeshop/testkube/releases/download/v1.10.2/testkube_1.10.2_Linux_x86_64.tar.gz"
      sha256 "3aaa35eeb533df5757834e19fb43e85364ff1b033e46dc10e4408dc83203c5fa"

      def install
        bin.install "kubectl-testkube"
        ln_s bin/"kubectl-testkube", bin/"tk"
        ln_s bin/"kubectl-testkube", bin/"testkube"
      end
    end
  end
end
