# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Testkube < Formula
  desc "Testkube - your somewhat opinionated and friendly Kubernetes testing framework!"
  homepage "https://testkube.io"
  version "2.1.53"
  license "MIT"

  depends_on "helm"
  depends_on "kubectl"

  on_macos do
    on_intel do
      url "https://github.com/kubeshop/testkube/releases/download/v2.1.53/testkube_2.1.53_Darwin_x86_64.tar.gz"
      sha256 "451220358ba4aae12c047c23567cadaa5963a9a33f14c666b4a6e747d43fb231"

      def install
        bin.install "kubectl-testkube"
        ln_s bin/"kubectl-testkube", bin/"tk"
        ln_s bin/"kubectl-testkube", bin/"testkube"
      end
    end
    on_arm do
      url "https://github.com/kubeshop/testkube/releases/download/v2.1.53/testkube_2.1.53_Darwin_arm64.tar.gz"
      sha256 "6a9ee49adc903133f340caf0522437112a27456003edba6b5339e3ff62155842"

      def install
        bin.install "kubectl-testkube"
        ln_s bin/"kubectl-testkube", bin/"tk"
        ln_s bin/"kubectl-testkube", bin/"testkube"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kubeshop/testkube/releases/download/v2.1.53/testkube_2.1.53_Linux_x86_64.tar.gz"
        sha256 "dfbdbf07597dc3da7805c4e4022779a0b8809a52e668155eeb70d30edf48e21b"

        def install
          bin.install "kubectl-testkube"
          ln_s bin/"kubectl-testkube", bin/"tk"
          ln_s bin/"kubectl-testkube", bin/"testkube"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kubeshop/testkube/releases/download/v2.1.53/testkube_2.1.53_Linux_arm64.tar.gz"
        sha256 "c952ef5dbf5908019f2ee3fe0d3b555161cc8a203a79d1d4f14b4ce52185a524"

        def install
          bin.install "kubectl-testkube"
          ln_s bin/"kubectl-testkube", bin/"tk"
          ln_s bin/"kubectl-testkube", bin/"testkube"
        end
      end
    end
  end
end
