# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Testkube < Formula
  desc "Testkube - your somewhat opinionated and friendly Kubernetes testing framework!"
  homepage "https://testkube.io"
  version "1.5.21"
  license "MIT"

  depends_on "helm"
  depends_on "kubectl"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubeshop/testkube/releases/download/v1.5.21/testkube_1.5.21_macOS_x86_64.tar.gz"
      sha256 "65f4e5ea3815c047243088c6f596486c0bdc0a71ae1867c2f1a99c3238fa6696"

      def install
        bin.install "kubectl-testkube"
        ln_s bin/"kubectl-testkube", bin/"tk"
        ln_s bin/"kubectl-testkube", bin/"testkube"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubeshop/testkube/releases/download/v1.5.21/testkube_1.5.21_macOS_arm64.tar.gz"
      sha256 "a81605598c628bf8f4fe2cad6289a29324055f70428ba840ea894680b9b90eb8"

      def install
        bin.install "kubectl-testkube"
        ln_s bin/"kubectl-testkube", bin/"tk"
        ln_s bin/"kubectl-testkube", bin/"testkube"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kubeshop/testkube/releases/download/v1.5.21/testkube_1.5.21_Linux_x86_64.tar.gz"
      sha256 "4335fc2a35b2002f5d0e63980bcdad2fdfad7964ef83e56eed9dbbe813f65f18"

      def install
        bin.install "kubectl-testkube"
        ln_s bin/"kubectl-testkube", bin/"tk"
        ln_s bin/"kubectl-testkube", bin/"testkube"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubeshop/testkube/releases/download/v1.5.21/testkube_1.5.21_Linux_arm64.tar.gz"
      sha256 "fc3d200339d701f0a4c23c05a4b1e84144b4b2bc0c2720ffb128139590411989"

      def install
        bin.install "kubectl-testkube"
        ln_s bin/"kubectl-testkube", bin/"tk"
        ln_s bin/"kubectl-testkube", bin/"testkube"
      end
    end
  end
end
